fixes UdaySravanK/RNSwipeButton#38
UdaySravanK/RNSwipeButton pull request #45
Opened 2020-09-01 21:57 UTC by mohamedmaged

In this pull request I solved Fixes #38 
I have added a new prop called isRTL that has a default value to false 
`       ...(enableRightToLeftSwipe ? ( isRTL ? styles.container: styles.containerRTL ) : (isRTL ? styles.containerRTL : styles.container)),
`
by adding this extra check the RTL layouts will behave as expected

2020-09-01 23:07 UTC, SallyHabib97 commented
Finally Someone did that 
THANKS 🙈

2020-09-02 18:27 UTC, UdaySravanK commented
Thanks for PR @mohamedmaged, I will take a look over the coming weekend.

2020-09-08 05:40 UTC, UdaySravanK requested changes
Hey @mohamedmaged I don't think we need a new prop, please check my comment. thanks!

2020-09-08 05:40 UTC, UdaySravanK commented on src/components/SwipeThumb/index.js
> +    ...(enableRightToLeftSwipe ? ( isRTL ? styles.container: styles.containerRTL ) : (isRTL ? styles.containerRTL : styles.container)),
Can you please try below things
1. Delete new prop 'isRTL' and try to use `I18nManager.isRTL`
2. Rename existing prop `enableRightToLeftSwipe` to `enableReverseSwipe`
3. By default for all RTL layouts swipe button should work as right to left swipe
Without any code changes, if we switch LTR to RTL then demo app should look like below screenshot
<img width="300" src="https://user-images.githubusercontent.com/7910545/92436997-931a7200-f16b-11ea-8649-c3cd5b7171a4.png" />

2020-09-09 09:46 UTC, mohamedmaged commented
I think yes we don't need the isRTL prop , thanks for pinting that out , I will be doing the changes you reuqests in the cming weekend

2020-09-12 01:40 UTC, mohamedmaged commented
@UdaySravanK  I did the changes you requested  I have made sure that By default for all RTL layouts swipe button should work as right to left swipe Without any code changes 

also removed the isRTL prop and used the I18nManager instead

2020-09-13 02:47 UTC, UdaySravanK requested changes
Hi Maged, Thanks for making changes. 
1. `enableReverseSwipe` not working. Can you please test and make necessary changes.
2. Please replace `enableRightToLeftSwipe` with `enableReverseSwipe` in `example/RNSwipeButtonDemo/App.js`

2020-09-13 02:47 UTC, UdaySravanK commented on docs/index.html
> +    <b>isRTL</b>: PropTypes.bool, <span style="color: blueviolet"> // for Right to left layout based Applications </span>
Please delete this

2020-09-13 03:34 UTC, UdaySravanK commented
> Hi Maged, Thanks for making changes.
> 
>     1. `enableReverseSwipe` not working. Can you please test and make necessary changes.
> 
>     2. Please replace `enableRightToLeftSwipe` with `enableReverseSwipe` in `example/RNSwipeButtonDemo/App.js` also update 'Right to left swipe enabled' to 'Reverse swipe enabled'

Since the logic looks correct, I tried to test it multiple times. It is working well. I'm not sure why it was not working at first attempt. Please make changes for point 2 and you too test for one last time. Then we are good to go.

2020-09-14 16:22 UTC, mohamedmaged commented
@UdaySravanK  I did the changes you requested , I have tested the app  one last time with and without RTL seems to be working fine

2020-09-14 17:15 UTC, UdaySravanK approved these changes
Appreciate your time. Nicely done 👍

2020-09-14 17:18 UTC, merged

2020-09-18 17:46 UTC, mohamedmaged commented
@UdaySravanK  thanks :')